# Generated by Django 5.2.4 on 2025-07-17 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntrepreneurProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=100)),
                ("custom_url", models.SlugField(unique=True)),
                ("bio", models.TextField()),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="entrepreneurs/profile/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="entrepreneurs/banner/"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "performance_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("social_media_handles", models.JSONField(blank=True, default=dict)),
                ("bank_details", models.JSONField(blank=True, default=dict)),
                ("crypto_wallets", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntrepreneurMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_views", models.IntegerField(default=0)),
                ("total_clicks", models.IntegerField(default=0)),
                ("total_sales", models.IntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "commission_earned",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("markup_earned", models.DecimalField(decimal_places=2, max_digits=12)),
                ("conversion_rate", models.FloatField()),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrepreneurs.entrepreneurprofile",
                    ),
                ),
            ],
        ),
    ]
