# Generated by Django 5.2.4 on 2025-07-17 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entrepreneurs", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntrepreneurStorefront",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("modern", "Modern"),
                            ("classic", "Classic"),
                        ],
                        default="default",
                        max_length=32,
                    ),
                ),
                ("custom_css", models.TextField(blank=True)),
                ("about_section", models.TextField(blank=True)),
                ("contact_info", models.JSONField(blank=True, default=dict)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("seo_title", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "entrepreneur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrepreneurs.entrepreneurprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("custom_description", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "storefront",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social.entrepreneurstorefront",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entrepreneurstorefront",
            name="featured_products",
            field=models.ManyToManyField(
                through="social.FeaturedProduct", to="products.product"
            ),
        ),
        migrations.CreateModel(
            name="ReferralTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_platform", models.CharField(max_length=32)),
                ("source_url", models.URLField()),
                ("utm_params", models.JSONField(blank=True, default=dict)),
                ("visitor_ip", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("session_id", models.CharField(max_length=255)),
                ("converted_to_sale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrepreneurs.entrepreneurprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[("story", "Story"), ("post", "Post"), ("ad", "Ad")],
                        max_length=32,
                    ),
                ),
                ("content", models.TextField()),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("scheduled_time", models.DateTimeField(null=True)),
                ("posted_time", models.DateTimeField(null=True)),
                ("platform_post_id", models.CharField(blank=True, max_length=255)),
                ("engagement_metrics", models.JSONField(blank=True, default=dict)),
                ("is_posted", models.BooleanField(default=False)),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entrepreneurs.entrepreneurprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
